POST http://localhost:7071/api/ChatGPT4oSimpleChatCompletion
Content-Type: application/json

{
    "system_text": "You are an AI assistant that helps people find information.",
    "image_url": "https://4.bp.blogspot.com/-C6D8IhOzTTI/XCDoJrzeZeI/AAAAAAABFTs/NoXurv2f6sYlN9Gxo7Lhjy2WX7FEIK17ACLcBGAs/s1600/Earthrise1_Apollo8AndersWeigang_2048.jpg",
    "user_text": "Describe this image"
}

###
POST http://localhost:7071/api/ChatGPT4oFullChatCompletion
Content-Type: application/json

{
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "You are an AI assistant that helps people find information."
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://i.pinimg.com/736x/81/86/df/8186dfb0730e083593d088f772d0739a.jpg"
                    }
                },
                {
                    "type": "text",
                    "text": "Describe this image and suggest 10 holdiay destinations base on it."
                }
            ]
        }
    ],
    "temperature": 0.7,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "max_tokens": 800,
    "stop": null,
    "stream": false
}

###
POST http://localhost:7071/api/chatgpt4osimplechatcompletion
Content-Type: application/json

{
    "system_text": "You are an AI assistant that helps users create lists of items in their homes to be included in their home insurance policies.",
    "image_url": "https://thewondercottage.com/wp-content/uploads/2019/07/img_2521.jpg",
    "user_text": "Examine this photo and list all the items in the photo that should be included in a house insurance policy.  Please respond with a JSON object and no additional text.  Do not wrap the response in a json or code block.

Follow these rules:
Category should be: Electronices, Furniture, Toy, Decor, Lighting, Personal or Other
CostCategory should only be low, medium or high
Do not include people or animals
The CostForFilter is a signle integer number based on the CostEsimate

Example Response:
{
    ""Name"": ""Living Room"",
    ""Description"": ""The photo show an image of a living room"",
    ""Instructions"": ""Save your receipts and photos"",
    ""Items"" : 
    [
        {
            ""Name"": ""Television"",
            ""Category"": ""Electronics"",
            ""CostCategory"": ""High"",
            ""CostEstimate"": ""£500 - £1000""
            ""CostForFilter"": 750
        },
        {
            ""Name"": ""XBox"",
            ""Category"": ""Electronics"",
            ""CostCategory"": ""Medium"",
            ""CostEstimate"": ""250 - 500"",
            ""CostForFilter"": 375
        },
    ]
}

JSON:"
}


###
POST https://chatgtp-4o.azurewebsites.net/api/chatgpt4osimplechatcompletion
Content-Type: application/json

{
    "system_text": "You are an AI assistant that helps people find information.",
    "image_url": "https://4.bp.blogspot.com/-C6D8IhOzTTI/XCDoJrzeZeI/AAAAAAABFTs/NoXurv2f6sYlN9Gxo7Lhjy2WX7FEIK17ACLcBGAs/s1600/Earthrise1_Apollo8AndersWeigang_2048.jpg",
    "user_text": "Describe this image"
}


###
POST https://chatgtp-4o.azurewebsites.net/api/chatgpt4ofullchatcompletion
Content-Type: application/json

{
    "messages": [
        {
            "role": "system",
            "content": [
                {
                    "type": "text",
                    "text": "You are an AI assistant that helps people find information."
                }
            ]
        },
        {
            "role": "user",
            "content": [
                {
                    "type": "image_url",
                    "image_url": {
                        "url": "https://i.pinimg.com/736x/81/86/df/8186dfb0730e083593d088f772d0739a.jpg"
                    }
                },
                {
                    "type": "text",
                    "text": "Describe this image and suggest 10 holdiay destinations base on it."
                }
            ]
        }
    ],
    "temperature": 0.7,
    "top_p": 0.95,
    "frequency_penalty": 0,
    "presence_penalty": 0,
    "max_tokens": 800,
    "stop": null,
    "stream": false
}


###
POST https://chatgtp-4o.azurewebsites.net/api/chatgpt4osimplechatcompletion
Content-Type: application/json

{
    "system_text": "You are an AI assistant that helps users create lists of items in their homes to be included in their home insurance policies.",
    "image_url": "https://thewondercottage.com/wp-content/uploads/2019/07/img_2521.jpg",
    "user_text": "Examine this photo and list all the items in the photo that should be included in a house insurance policy.  Please respond with a JSON object and no additional text.  Do not wrap the response in a json or code block.

Follow these rules:
Category should be: Electronices, Furniture, Toy, Decor, Lighting, Personal or Other
CostCategory should only be low, medium or high
Do not include people or animals
The CostForFilter is a signle integer number based on the CostEsimate

Example Response:
{
    ""Name"": ""Living Room"",
    ""Description"": ""The photo show an image of a living room"",
    ""Instructions"": ""Save your receipts and photos"",
    ""Items"" : 
    [
        {
            ""Name"": ""Television"",
            ""Category"": ""Electronics"",
            ""CostCategory"": ""High"",
            ""CostEstimate"": ""£500 - £1000""
            ""CostForFilter"": 750
        },
        {
            ""Name"": ""XBox"",
            ""Category"": ""Electronics"",
            ""CostCategory"": ""Medium"",
            ""CostEstimate"": ""250 - 500"",
            ""CostForFilter"": 375
        },
    ]
}

JSON:"
}
